# ============================================
# $Id: Makefile,v 1.2 2002/02/05 16:34:07 eric Exp $
# $Log: Makefile,v $
# Revision 1.2  2002/02/05 16:34:07  eric
# decoupage pour FREEDOM-LIB
#
# Revision 1.1  2001/11/09 09:43:59  eric
# gestion documentaire
#
# Revision 1.1  2001/06/13 14:41:44  eric
# contact address book
#
# ============================================

appname=$(applib)

include $(utildir)/PubRule
