#!/bin/bash
if [ "$freedom_context" == "" ]; then
    #load environement variable for freedom
  . /etc/freedom.conf
   wchoose -b
fi

#------------------------------
#post installation
#------------------------------
if [ "$1" = "I" ] ; then
    # add plug in footer
  "$wpub"/wsh.php --app=APPMNG --action=PARAM_MOD --appid=1 --aname=CORE_PLUGZONE --atype=G --val=FREEDOM:SPEEDSEARCH

  
fi
#------------------------------
#post update
#------------------------------
if [ "$1" = "U" ] ; then
 echo;


fi
