# ============================================
# $Id: Makefile,v 1.2 2006/11/22 10:33:59 eric Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(shell basename `pwd` | tr [a-z] [A-Z])

include $(utildir)/PubRule
