# ============================================
# $Id: Makefile,v 1.1 2002/01/08 12:41:33 eric Exp $
# ============================================


export targetdir
export utildir

SUBDIR= Core Users Authent Appmng Access


include $(utildir)/PubRule


DISTFILES = $(SUBDIR) Makefile
