# ============================================
# $Id: Makefile,v 1.1 2002/01/08 12:41:33 eric Exp $
# ============================================

export targetdir
export utildir

SUBDIR = Authent Core Dav Fdc Fdl Fgsearch Freedom Fusers Generic Vault

include $(utildir)/PubRule
