#!/usr/bin/php -q
<?php

$pubdir="/home/httpd/what";

include("WHAT/Lib.Common.php");
include("WHAT/wncurses.php");

global $_SERVER;

if ($_SERVER['HTTP_HOST'] != "")     {
  print "<BR><H1>:~(</H1>";
  exit;
}


$dbank=getenv("dbanakeen");
$virtual=getenv("snwhat"); // server name
$dbaccess="user=anakeen dbname=$dbank";
$dbfree="free$dbank";
if ($argv[1]!="") $dbfree=$argv[1];


ncurses_winit("WHAT Create Database");
ncurses_getmaxyx(&$fullscreen, $lines, $columns);

$IP=chop(`hostname -i`);
ncurses_color_set(6);
ncurses_mvaddstr(2,5,sprintf(_("Database: %s"), $dbaccess));
ncurses_mvaddstr(4,5,sprintf(_("Virtual Host: %s on %s"), $virtual,$IP));
ncurses_refresh();







//---------------------------------------------------






$dbid=@pg_connect($dbaccess);

$wsh=array(); // application update
$migr=array();// migration
$post=array();// post install 
$pre=array(); // pre install 
$dump=array();
print "\n";
array_shift($argv);
$args=implode(" ",$argv);
if ($dbid) {

  $small = ncurses_newwin(10, 50, 7, 25);
  if (!$small) {
    ncurses_exit();
  }
  ncurses_wborder($small,0,0, 0,0, 0,0, 0,0);
  ncurses_wcolor_set($small,1);
  ncurses_mvwaddstr($small, 4, 5, _("Access to default database : granted "));
  ncurses_wattron($small,NCURSES_A_BOLD); 
  ncurses_mvwaddstr($small, 5, 5, _("Already created. creation aborted"));
  ncurses_wattroff($small,NCURSES_A_BOLD);
// show our handiwork and refresh our small window
  ncurses_wrefresh($small);
  $pressed = ncurses_getch();// wait for a user keypress
  ncurses_end();// clean up our screen
  exit;

} 
  


$actions[] = "mkdir -p $pubdir/virtual/$dbank/FDLGEN";
$actions[] = "cd $pubdir/FDLGEN;ln -s  ../virtual/$dbank/FDLGEN ".strtoupper($dbfree);
$actions[] = "sed -e 's/dbname=anakeen/dbname=$dbank/' $pubdir/dbaccess.php > $pubdir/virtual/$dbank/dbaccess.php";
$actions[] = "sed -e 's/@DBNAME@/$dbank/g' $pubdir/httpd.pam.in > /etc/pam.d/httpd_$dbank"; 
$actions[] = "sed -e 's/@DBNAME@/anakeen/g'  -e 's/@IP@/$IP/g' -e 's/@VIRTUALNAME@/".trim(`hostname -f`)."/g' $pubdir/apachevi.conf.in > /etc/httpd/httpd.conf/71_mod_what_anakeen.conf";
$actions[] = "sed -e 's/@DBNAME@/$dbank/g' -e 's/@dbname@/".strtolower($dbank)."/g' -e 's/@Dbname@/".ucfirst(strtolower($dbank))."/g' -e 's/@IP@/$IP/g' -e 's/@VIRTUALNAME@/$virtual/g' $pubdir/apachev.conf.in > /etc/httpd/httpd.conf/71_mod_what_$dbank.conf";
$actions[] = "$pubdir/CORE/CORE_post I ";

$actions[] = "$pubdir/wsh.php --api=appadmin --method=update --appname=CORE";
$actions[] = "echo \"update paramv set val= str_replace(val,'dbname=anakeen','dbname=$dbank') where val ~ 'dbname'\" | psql $dbank anakeen";
$actions[] = "$pubdir/wsh.php --api=appadmin --method=init --appname=FDL";
$actions[] = "$pubdir/wsh.php --api=set_param --param=FREEDOM_DB --value=\"user=anakeen dbname=$dbfree\"";
$actions[] = "$pubdir/wsh.php --api=set_param --param=CORE_CLIENT --value=\"$dbank\"";
$actions[] = "$pubdir/wsh.php --api=set_param --param=CORE_RFOOT --value=\"$dbfree\"";

$actions[] = "$pubdir/FDL/FDL_post I ";
// $actions[] = "mkdir -p $pubdir/FDLGEN/".strtoupper($dbfree);
$actions[] = "$pubdir/wsh.php --api=appadmin --method=update --appname=FDL";
$actions[] = "$pubdir/CORE/CORE_post U ";
$actions[] = "$pubdir/FDL/FDL_post U ";



  
  


  

    


ncurses_execute($actions);

ncurses_mvaddstr($lines-2, 4, _("Finished. See file log /tmp/whatchk.log"));
$pressed = ncurses_getch();// wait for a user keypress
ncurses_end();
?>