#!/bin/bash -e

DIRNAME=`dirname "$0"`
REAL_DIRNAME=`cd "$DIRNAME" 1> /dev/null 2>&1 && pwd`
if [ -z "$REAL_DIRNAME" ]; then
    echo "Could not get real dir name from '$0'."
    exit 1
fi
export wpub=$REAL_DIRNAME

shopt -s nullglob

function main {
    if [ "$WHATTEXT_GOT_LOCK" = "yes" ]; then
	# The lock has been obtained, so keep on processing...
	whattext
    else
	# Try to obtain the lock and re-execute myself
	WHATTEXT_GOT_LOCK=yes "$wpub/programs/flock" "$0".lock "$0" "$@"
    fi
}

function whattext ()
{
    ntf="$wpub/locale/.gettextnumber"
    if [ ! -f "$ntf" ]; then
        echo "0" > "$ntf"
    fi
    numberone=`cat "$ntf"`
    numbertwo=`date +"%s"`
    today=`date "+%F %T"`
    for lang_dir in "$wpub"/locale/*; do
        if [ ! -d "$lang_dir/LC_MESSAGES" ]; then
            continue
        fi           

        pushd "$lang_dir/LC_MESSAGES" >/dev/null
        rm -f freedom-catalog*.mo # old catalogs
        if [ -f "main-catalog.mo" ]; then
            mv -f main-catalog.mo main-catalog.mo.old 
        fi

        find . -type l -name "main-catalog[0-9]*.mo" -exec /bin/rm {} \;

        if [ -h "main-catalog$numberone.mo" ]; then
            \rm "main-catalog$numberone.mo"
        fi

        for mo in *.mo ; do
            msgunfmt --force-po "$mo" -o "$mo.po"
        done

        if [ -d "./src" ]; then
            for po in ./src/*.po ; do
                    msgfmt -c -o /dev/null $po # verify syntax
            done
            msgcat --use-first -o allmo.tmp  header*.po customFamily*po ./src/*.po *.po
            msgfmt -o main-catalog.mo allmo.tmp
            rm allmo.tmp
        else
            msgcat --use-first -o allmo.tmp  header*.po *.po
            msgfmt -o main-catalog.mo allmo.tmp
            rm allmo.tmp
        fi

        rm -f *.po *.old

        if [ ! -a "main-catalog$numbertwo.mo" ]; then
            \ln -s main-catalog.mo "main-catalog$numbertwo.mo" && echo "$numbertwo" > "$ntf"

        fi
        popd >/dev/null

        if [ -d "$lang_dir/js" ]; then
            pushd "$lang_dir/js" > /dev/null
            echo '{"fdl:creationDate":"'$today'"}'> null-mo.js
            if [ -d "./src" ]; then
                for po in ./src/*.po ; do
                    msgfmt -c -o /dev/null $po
                    php "$wpub/programs/po2js" $po > $po.mo.js
                    jsFile=`basename "$po" ".po"`".js"
                    jsFile="catalog-"${jsFile#js_}
                    cp "$po.mo.js" $jsFile
                done
                php "$wpub/programs/json_concat" *mo.js ./src/*mo.js > catalog.js
                
                \rm -f ./src/*mo.js
            else
                php "$wpub/programs/json_concat" *mo.js  > catalog.js 
            fi
            \rm null-mo.js
            popd >/dev/null
        fi
    done
}

main "$@"
