#!/bin/bash

DIRNAME=`dirname "$0"`
REAL_DIRNAME=`cd "$DIRNAME" 1> /dev/null 2>&1 && pwd`
if [ -z "$REAL_DIRNAME" ]; then
    echo "Could not get real dir name from '$0'."
    exit 1
fi
export wpub=$REAL_DIRNAME

core_environment="$wpub/programs/core_environment"
if [ ! -x "$core_environment" ]; then
    echo "'$core_environment' not found or not executable."
    exit 1
fi
. "$core_environment"


# link images file to be used in several applications
if [ ! -d "$wpub/Images" ] ; then
    mkdir "$wpub/Images"
fi
if [ ! -d "$wpub/Docs" ] ; then
    mkdir "$wpub/Docs"
fi
pushd "$wpub/Images" > /dev/null
ln -sf ../*/Images/* .
popd > /dev/null

rm -f "$wpub"/var/cache/image/*png
rm -f "$wpub"/var/cache/image/*gif
rm -f "$wpub"/var/cache/image/*xml
rm -f "$wpub"/var/cache/image/*src
rm -f "$wpub"/.autoloader.cache

pushd "$wpub/Docs" > /dev/null
ln -sf ../*/Docs/* .
popd > /dev/null
#refresh version identificator
"$wpub/wsh.php" --api=refreshjsversion >/dev/null
RET=$?
if [ $RET -ne 0 ]; then
    echo "Error regenerating autoloader cache or refreshing JS version"
    exit $RET
fi

#change pg mode connection
cdb=`"$wpub/wsh.php" --api=get_param --param=CORE_DBCONNECT`
if [ "$cdb" == 'persistent' ] ; then
  sed -ibak -e"s/pg_connect/pg_pconnect/g" "$wpub/WHAT/Lib.Common.php"
else
  sed -ibak -e"s/pg_pconnect/pg_connect/g" "$wpub/WHAT/Lib.Common.php"
fi

"$wpub/wsh.php" --api=setStyle >/dev/null
RET=$?
if [ $RET -ne 0 ]; then
    echo "Error setting style"
    exit $RET
fi

if [ -f "$wpub/maintenance.lock" ]; then
    rm -f "$wpub/maintenance.lock"
fi