#!/bin/bash

pubdir="/home/httpd/what";
/bin/cp $pubdir/WHAT/index.php $pubdir


# link images file to be used in several applications
if [ ! -d $pubdir/Images ] ; then
    mkdir $pubdir/Images
fi
pushd $pubdir/Images > /dev/null
ln -sf ../*/Images/* .
popd > /dev/null
