#!/bin/bash
if [ "$freedom_context" == "" ]; then
  . /etc/freedom.conf
   wchoose -b
fi

if [ -z "$wpub" ]; then
    echo "Warning: wpub is not set. Exiting now !"
    exit 0
fi

touch $wpub/maintenance.lock
echo "check update needed ($wpub/wcheck)"