#!/bin/bash

if [ "$freedom_context" == "" ]; then
  . /etc/freedom.conf
  if [ ! -f "$wpub/context/default/dbaccess.php" ]; then
    # not initialized yet
    exit 0
   fi
   wchoose -b
fi

if [ -z "$wpub" ]; then
    echo "Warning: wpub is not set. Exiting now !"
    exit 0
fi

touch $wpub/maintenance.lock
echo "check update needed ($wpub/wcheck)"