# ============================================
# $Id: Makefile,v 1.3 2004/08/23 12:48:19 eric Exp $
# ============================================


export targetdir
export utildir

SUBDIR= Green Red Aqua Blue


include $(utildir)/PubRule


DISTFILES = $(SUBDIR) Makefile
