# ============================================
# $Id: Makefile,v 1.8 2006/06/21 10:14:26 eric Exp $
# ============================================


export targetdir
export utildir

SUBDIR= Default Green Red Aqua Blue Caramel Black Darkblue Brushed


include $(utildir)/PubRule


DISTFILES = $(SUBDIR) Makefile
