# ============================================
# $Id: Makefile,v 1.4 2005/10/06 10:18:09 marc Exp $
# ============================================


export targetdir
export utildir

SUBDIR= Green Red Aqua Blue Caramel


include $(utildir)/PubRule


DISTFILES = $(SUBDIR) Makefile
