# ============================================
# $Id: Makefile,v 1.1 2002/02/18 13:37:21 eric Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(shell basename `pwd` | tr [a-z] [A-Z])

export appname

include $(utildir)/PubRule
