# ============================================
# $Id: Makefile,v 1.2 2007/08/16 16:35:59 eric Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(shell basename `pwd` | tr [a-z] [A-Z])

export appname

include $(utildir)/PubRule
