# ============================================
# $Id: Makefile,v 1.1 2001/11/09 09:41:14 eric Exp $
# ============================================

export utildir

SUBDIR= data

include $(utildir)/PubRule

DISTFILES = $(SUBDIR) Makefile
