# ============================================
# $Id: Makefile,v 1.1 2002/02/05 16:34:07 eric Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(shell basename `pwd` | tr [a-z] [A-Z])

export appname


include $(utildir)/PubRule



