# ============================================
# $Id: Makefile,v 1.3 2005/11/14 11:36:50 marc Exp $
# ============================================

appname = mcal
export appname

SUBDIR=
include $(utildir)/PubRule

DISTFILES +=  $(SUBDIR) $(wildcard *.js) $(wildcard *.php) $(wildcard *.png) $(wildcard *.gif)
