# ============================================
# $Id: Makefile,v 1.1 2005/11/10 15:43:56 eric Exp $
# ============================================

# get the new appname (basename in uppercase)

include $(utildir)/PubRule


