# ============================================
# $Id: Makefile,v 1.1 2007/10/17 04:47:32 marc Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(shell basename `pwd` | tr [a-z] [A-Z])

export appname


include $(utildir)/PubRule


