# ============================================
# $Id: Makefile,v 1.2 2006/11/06 15:36:01 eric Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(shell basename `pwd` | tr [a-z] [A-Z])

export appname

include $(utildir)/PubRule
