# ============================================
# $Id: Makefile,v 1.1 2007/02/19 16:25:40 marc Exp $
# ============================================
appname = $(shell basename `pwd` | tr [a-z] [A-Z])
export appname
include $(utildir)/PubRule
