# ============================================
# $Id: Makefile,v 1.1 2004/08/12 10:24:44 eric Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(shell basename `pwd` | tr [a-z] [A-Z])

export appname

include $(utildir)/PubRule
