# ============================================
# $Id: Makefile,v 1.1 2003/01/24 14:10:46 eric Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(applib)

export appname


include $(utildir)/PubRule



