# ============================================
# $Id: Makefile,v 1.1 2002/01/08 12:41:34 eric Exp $
# ============================================

export targetdir
export utildir

SUBDIR = Access Authent Core Dav Fdc Fdl Fgsearch Freedom Fusers Generic

include $(utildir)/PubRule
