# ============================================
# $Id: Makefile,v 1.1 2002/01/08 12:41:34 eric Exp $
# ============================================

export targetdir
export utildir

SUBDIR = Access Appmng Authent Core Data Dav Fdc Fdl Fgsearch Freedom Fusers Generic Onefam Usercard Vault

include $(utildir)/PubRule
