# ============================================
# $Id: Makefile,v 1.4 2004/09/09 08:19:39 caroline Exp $
# ============================================

export targetdir
export utildir

#SUBDIR= Users Freedom Site Product Contract Incident Usercard 

include $(utildir)/PubRule

DISTFILES+=$(SUBDIR)
