# ============================================
# $Id: Makefile,v 1.2 2004/09/09 08:20:11 caroline Exp $
# ============================================


export targetdir
export utildir

SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+=$(SUBDIR)
