# ============================================
# $Id: Makefile,v 1.3 2004/10/29 09:33:59 eric Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+=$(SUBDIR)
