# ============================================
# $Id: Makefile,v 1.1 2002/04/23 07:46:41 eric Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(shell basename `pwd` | tr [a-z] [A-Z])

export appname

include $(utildir)/PubRule
