# ============================================
# $Id: Makefile,v 1.4 2007/06/29 09:46:53 yannick Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+=changelog.in compat control copyright dirs docs postinst prerm rules
