# ============================================
# $Id: Makefile,v 1.2 2007/06/26 20:13:31 yannick Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+=changelog compat control copyright dirs docs postinst.ex prerm.ex rules
