# ============================================
# $Id: Makefile,v 1.5 2007/07/06 12:45:34 yannick Exp $
# ============================================


export targetdir
export utildir

#SUBDIR= Users


include $(utildir)/PubRule


DISTFILES+=changelog compat control copyright dirs docs postinst prerm rules debian.patch freedom.conf
