# ============================================
# $Id: Makefile,v 1.1 2002/02/13 14:31:59 eric Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(applib)

export appname

include $(utildir)/PubRule
