# ============================================
# $Id: Makefile,v 1.1 2006/05/30 16:32:46 eric Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(shell basename `pwd` | tr [a-z] [A-Z])

export appname

include $(utildir)/PubRule
