# ============================================
# $Id: Makefile,v 1.2 2007/05/04 08:11:53 eric Exp $
# ============================================


SUBDIR= fr
include $(utildir)/PubRule
DISTFILES += $(SUBDIR)
