# ============================================
# $Id: Makefile,v 1.1 2002/01/08 12:41:34 eric Exp $
# ============================================

export targetdir
export utildir

SUBDIR = Authent Core Dav Fdc Fdl Freedom Generic Usercard

include $(utildir)/PubRule
