# ============================================
# $Id: Makefile,v 1.2 2008/06/27 14:28:56 eric Exp $
# ============================================

appname = WHAT

SUBDIR= providers

include $(utildir)/PubRule
