# ============================================
# $Id: Makefile,v 1.1 2008/06/10 15:01:43 jerome Exp $
# ============================================



SUBDIR=

appname = WHAT/providers/basic

include $(utildir)/PubRule

DISTFILES = $(SUBDIR) Makefile

