# ============================================
# $Id: Makefile,v 1.1 2002/01/08 12:41:34 eric Exp $
# ============================================

export targetdir
export utildir

SUBDIR = Appmng Authent Contract Core Dav Fdc Fdl Fgsearch Freedom Generic Site Users Vault

include $(utildir)/PubRule
