# ============================================
# $Id: Makefile,v 1.1 2001/11/16 10:11:06 marc Exp $
# $Log: Makefile,v $
# Revision 1.1  2001/11/16 10:11:06  marc
# V0_0_1 Initial release, see CHANGELOG
#
# Revision 1.1  2001/11/09 09:43:59  eric
# gestion documentaire
#
# Revision 1.1  2001/06/13 14:41:44  eric
# contact address book
#
# ============================================


include $(utildir)/PubRule
