# ============================================
# $Id: Makefile,v 1.1 2002/02/13 14:31:59 eric Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(shell basename `pwd` | tr [a-z] [A-Z])

export appname
SUBDIR=Schemas
include $(utildir)/PubRule
