# ============================================
# $Id: Makefile,v 1.2 2003/03/06 18:03:54 eric Exp $
# ============================================




include $(utildir)/PubRule

publish: $(pubdir)/log.sh

$(pubdir)/log.sh: log.sh
	cp $< $@

DISTFILES += log.sh
