# ============================================
# $Id: Makefile,v 1.1 2003/05/22 09:00:43 eric Exp $
# ============================================

appname = htmlarea
export appname

SUBDIR= images popups
include $(utildir)/PubRule

DISTFILES +=  $(SUBDIR) $(wildcard *.html) $(wildcard *.txt)
