# ============================================
# $Id: Makefile,v 1.1 2006/11/03 16:22:48 eric Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(shell basename `pwd` | tr [a-z] [A-Z])

export appname

include $(utildir)/PubRule
