# ============================================
# $Id: Makefile,v 1.1 2004/10/18 08:46:13 marc Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(applib)

export appname


include $(utildir)/PubRule



