# ============================================
# $Id: Makefile,v 1.2 2008/06/27 14:28:56 eric Exp $
# ============================================



SUBDIR=

appname = WHAT/providers/html

include $(utildir)/PubRule

DISTFILES += $(SUBDIR) Makefile

