# ============================================
# $Id: Makefile,v 1.1 2005/07/29 08:15:31 eric Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(shell basename `pwd` | tr [a-z] [A-Z])

export appname

include $(utildir)/PubRule
