# ============================================
# $Id: Makefile,v 1.1 2005/07/29 08:15:31 eric Exp $
# ============================================

export targetdir
export utildir


include $(utildir)/PubRule

