# ============================================
# $Id: Makefile,v 1.1 2002/01/08 12:42:37 eric Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(shell basename `pwd` | tr [a-z] [A-Z])

export appname

include $(utildir)/PubRule
