# ============================================
# $Id: Makefile,v 1.1 2005/10/26 13:23:33 eric Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(shell basename `pwd` | tr [a-z] [A-Z])

export appname


include $(utildir)/PubRule



