# ============================================
# $Id: Makefile,v 1.1 2004/08/27 14:12:02 eric Exp $
# ============================================

appname = jscalendar
export appname

SUBDIR= lang
include $(utildir)/PubRule

DISTFILES +=  $(SUBDIR) $(wildcard *.html) $(wildcard *.txt)
