#!/bin/bash
if [ "$freedom_context" == "" ]; then
    #load environement variable for freedom
    . /etc/freedom.conf
    wchoose -b
fi

. "$wpub/log.sh"
. "$wpub/libutil.sh"

#------------------------------
#post installation
#------------------------------
if [ "$1" = "I" ] ; then
    PGSERVICE="$pgservice_core" psql -f "$wpub/DAV/dav-pg.sql"
    PGSERVICE="$pgservice_core" psql -c "UPDATE paramv SET val='service=''$pgservice_core''' WHERE name='WEBDAV_DB'"
          
fi

#------------------------------
#post update
#------------------------------
if [ "$1" = "U" ] ; then
    
	log "Setting WEBDAV_DB in paramv..."
        PGSERVICE="$pgservice_core" psql -c "select * from dav.locks" > /dev/null
        RET=$?
        if [ $RET -ne 0 ]; then
            PGSERVICE="$pgservice_core" psql -f "$wpub/DAV/dav-pg.sql"
            
        fi
	PGSERVICE="$pgservice_core" psql -c "UPDATE paramv SET val='service=''$pgservice_core''' WHERE name='WEBDAV_DB'"
	RET=$?
	if [ $RET -ne 0 ]; then
	    echo "Error setting WEBDAV_DB"
	    exit $RET
	fi
    
fi

#------------------------------
#post uninstallation
#------------------------------
if [ "$1" = "D" ] ; then
    echo
fi
