#!/bin/bash

if [ -z "$pgservice_core" ]; then
    echo "Env variable pgservice_core is empty !"
    echo "Check your context for missing or misconfigured environment variables."
    exit 1
fi

. "$wpub/log.sh"
. "$wpub/libutil.sh"

#------------------------------
#post installation
#------------------------------
if [ "$1" = "I" ] ; then
    PGSERVICE="$pgservice_core" psql -f "$wpub/DAV/dav-pg.sql"
fi

#------------------------------
#post update
#------------------------------
if [ "$1" = "U" ] ; then
    
	log "Setting WEBDAV_DB in paramv..."
        PGSERVICE="$pgservice_core" psql -c "select * from dav.locks" > /dev/null
        RET=$?
        if [ $RET -ne 0 ]; then
            PGSERVICE="$pgservice_core" psql -f "$wpub/DAV/dav-pg.sql"
        fi

fi

#------------------------------
#post uninstallation
#------------------------------
if [ "$1" = "D" ] ; then
    echo
fi
