# ============================================
# $Id: Makefile,v 1.3 2008/08/12 13:51:18 jerome Exp $
# ============================================



SUBDIR= Session Appmng Database Debug Form Layout Mail Authenticator Authent


include $(utildir)/PubRule

DISTFILES = $(SUBDIR) Makefile

