# ============================================
# $Id: Makefile,v 1.4 2009/01/16 15:47:53 jerome Exp $
# ============================================

export targetdir
export utildir

SUBDIR = Appmng Authent Authenticator Crontab Data Database Dav Debug Fdl Form Layout Mail Session Users Vault

include $(utildir)/PubRule
