# ============================================
# $Id: Makefile,v 1.2 2005/09/07 14:50:55 yannick Exp $
# ============================================

# get the new appname (basename in uppercase)
appname = $(shell basename `pwd` | tr [a-z] [A-Z])

export appname


include $(utildir)/PubRule

DISTFILES += appadmin.php.in updateclass.php.in



