#!/bin/bash
defaultlog=/var/log/Core_Install.log

# $1 : message
log() {
    echo `date +"%b %e %T"` `hostname -s` $0 $1 >> $defaultlog
    return 0
}


#$1 : login
#$2 : cmde
sulog() {
    status=1

    log "su $1 '$2'"
    su - $1 -c "$2 2>&1 > /tmp/log$$;echo \$? > /tmp/logst$$"
    status=$?
    if [ $status -eq 0 ] ; then
        if [ -f /tmp/logst$$ ]; then
            status=`cat /tmp/logst$$`
            /bin/rm /tmp/logst$$
        fi
    fi
    # log stderr and stdout of child process
    if [ -f /tmp/log$$ ]; then
        log "`cat /tmp/log$$`"
        rm /tmp/log$$
    fi
    return $status
}

#------------------------------
#post installation
#------------------------------
if [ "$1" = "I" ] ; then

  run=`pidof postmaster`
  if [ "x$run" = "x" ] ; then
    log "postgresql is not running ..Init is delayed"
    exit 1
  fi

  log "Create anakeen database"
  sulog postgres "createdb --encoding LATIN1 anakeen"
  
  log "Create anakeen database user"
  sulog postgres "createuser -d -a anakeen" 
 
  log "Add plpgsql language"
  sulog postgres "createlang --dbname=anakeen --pglib=/usr/lib/pgsql plpgsql"

  log "Add plpgsql functions"
  sulog postgres "psql anakeen anakeen -f /home/httpd/what/WHAT/getprivilege.sql"

  log "Register DB anakeen for automatic dump"
  ll=0
  if [ -f /etc/ankpsql-tools/base-list ] ; then
    ll=`cat /etc/ankpsql-tools/base-list | grep "^anakeen$" | wc -l`
  fi
  if [ $ll -eq 0 ]; then 
    echo "Register DB anakeen for automatic dump"
    echo "anakeen" >> /etc/ankpsql-tools/base-list
  fi



# Add What log facility in syslog
  echo "local6.info				/var/log/what.log" >> /etc/syslog.conf
  /etc/rc.d/init.d/syslog restart
  echo "/var/log/what.log {"               >  /etc/logrotate.d/what
  echo "   missingok"                      >> /etc/logrotate.d/what
  echo "   postrotate"                     >> /etc/logrotate.d/what
  echo "   /usr/bin/killall -HUP syslogd"  >> /etc/logrotate.d/what
  echo "   endscript"                      >> /etc/logrotate.d/what
  echo "}"                                 >> /etc/logrotate.d/what



fi


#------------------------------
#post update
#------------------------------
if [ "$1" = "U" ] ; then

  #add permission functionnalities
  su - postgres -c "psql anakeen anakeen -f /home/httpd/what/WHAT/getprivilege.sql"
  /home/httpd/what/wsh.php  --api=import_style --name=RED
  /home/httpd/what/wsh.php  --api=import_style --name=GREEN
  echo 'delete from permission where abs(id_acl) not in (select id from acl where acl.id_application=permission.id_application)' | psql anakeen anakeen

fi
#------------------------------
#post uninstallation
#------------------------------
if [ "$1" = "D" ] ; then

  set -e

  grep -v 'Include %{destdir}/apache.conf' /etc/httpd/conf/httpd.conf > /tmp/httpd.conf
  mv /tmp/httpd.conf /etc/httpd/conf/httpd.conf

  # Remove what from syslog
  echo "Remove what.log from syslog"
  cp /etc/syslog.conf /etc/syslog.conf.sav
  cat /etc/syslog.conf.sav | grep -v "^local6.*/var/log/what.log.*$" > /etc/syslog.conf
  /etc/rc.d/init.d/syslog restart
  rm -f /etc/logrotate.d/what

  # drop anakeen database and user
  log "The anakeen database will be dropped, we save a dump in /tmp/anakeen$$.dump"
  sulog  postgres  "pg_dump -d anakeen >/tmp/anakeen$$.dump"
  sulog  postgres  "dropuser anakeen" 
  sulog  postgres  "dropdb anakeen"

  log "Unregister DB anakeen for automatic dump"
  mv /etc/ankpsql-tools/base-list /etc/ankpsql-tools/base-list.old
  cat /etc/ankpsql-tools/base-list.old | grep -v "^anakeen$" > /etc/ankpsql-tools/base-list
  rm -f /etc/ankpsql-tools/base-list.old
fi

exit 0
